### ISSUE TITLE
Getting working with Builder and Flatpak

### ISSUE THREAD

**Issue by bunglesss** [slavaandrejev/cppgir-gtk#1]
I had a bit of a go at this. I got stuck at first as it needed Boost. I managed to sort that, but now get the error below.

subprojects/cppgir/meson.build:28:22: ERROR: C++ header 'fmt/format.h' not found

Any idea what to do about this?

**Comment by slavaandrejev** [comment]
I appreciate your interest. You need the [fmt](https://github.com/fmtlib/fmt) library available for Meson. I don't know how to make it available using Flatpack.

**Comment by bunglesss** [comment]
Found somewhere to copy it from here - https://github.com/flathub/tv.kodi.Kodi/blob/master/tv.kodi.Kodi.yml
